ANIME_REQ = ['title',
             'anilist_id',
             'mal_id',
             'tmdb_id',
             'formats',
             'status',
             'year',
             'season',
             'genres',
             'nsfw',
             'with_episodes']