#  MIT License
#
#  Copyright (c) 2022 by exersalza
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

genres = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Ecchi",
    "Fantasy",
    "Horror",
    "Mahou Shoujo",
    "Mecha",
    "Music",
    "Mystery",
    "Psychological",
    "Romance",
    "Sci-Fi",
    "Slice Of Life",
    "Sports",
    "Supernatural",
    "Thriller",
    "Anti-Hero",
    "Ensemble Cast",
    "Female Protagonist",
    "Male Protagonist",
    "Office Lady",
    "Primarily Adult Cast",
    "Primarily Child Cast",
    "Primarily Female Cast",
    "Primarily Male Cast",
    "Villainess",
    "Age Regression",
    "Agender",
    "Aliens",
    "Amnesia",
    "Artificial Intelligence",
    "Asexual",
    "Butler",
    "Centaur",
    "Chimera",
    "Chuunibyou",
    "Cosplay",
    "Crossdressing",
    "Delinquents",
    "Demons",
    "Detective",
    "Dinosaurs",
    "Dissociative Identities",
    "Dragons",
    "Dullahan",
    "Elf",
    "Ghost",
    "Goblin",
    "Gods",
    "Gyaru",
    "Hikikomori",
    "Idol",
    "Kemonomimi",
    "Kuudere",
    "Maids",
    "Mermaid",
    "Monster Girl",
    "Nekomimi",
    "Ninja",
    "Nudity",
    "Nun",
    "Oiran",
    "Ojou-Sama",
    "Pirates",
    "Robots",
    "Samurai",
    "Shrine Maiden",
    "Skeleton",
    "Succubus",
    "Tanned Skin",
    "Teacher",
    "Tsundere",
    "Twins",
    "Vampire",
    "Vikings",
    "Werewolf",
    "Witch",
    "Yandere",
    "Zombie",
    "Josei",
    "Kids",
    "Seinen",
    "Shoujo",
    "Shounen",
    "Bar",
    "Circus",
    "College",
    "Dungeon",
    "Foreign",
    "Language Barrier",
    "Outdoor",
    "Rural",
    "School",
    "School Club",
    "Urban",
    "Work",
    "Achronological Order",
    "Anachronism",
    "Dystopian",
    "Historical",
    "Time Skip",
    "Afterlife",
    "Alternate Universe",
    "Augmented Reality",
    "Post-Apocalyptic",
    "Space",
    "Urban Fantasy",
    "Virtual World",
    "4-Koma",
    "Achromatic",
    "Advertisement",
    "Anthology",
    "CGI",
    "Episodic",
    "Flash",
    "Full CGI",
    "Full Color",
    "No Dialogue",
    "POV",
    "Puppetry",
    "Rotoscoping",
    "Stop Motion",
    "Archery",
    "Battle Royale",
    "Espionage",
    "Fugitive",
    "Guns",
    "Martial Arts",
    "Swordplay",
    "Acting",
    "Calligraphy",
    "Classic Literature",
    "Drawing",
    "Fashion",
    "Food",
    "Photography",
    "Rakugo",
    "Writing",
    "Band",
    "Dancing",
    "Musical",
    "Parody",
    "Satire",
    "Slapstick",
    "Surreal Comedy",
    "Bullying",
    "Coming Of Age",
    "Conspiracy",
    "Rehabilitation",
    "Revenge",
    "Tragedy",
    "Body Swapping",
    "Cultivation",
    "Fairy Tale",
    "Henshin",
    "Isekai",
    "Kaiju",
    "Magic",
    "Mythology",
    "Shapeshifting",
    "Steampunk",
    "Super Power",
    "Superhero",
    "Wuxia",
    "Youkai",
    "Video Games",
    "Card Battle",
    "Go",
    "Karuta",
    "Mahjong",
    "Poker",
    "Shogi",
    "Airsoft",
    "American Football",
    "Athletics",
    "Badminton",
    "Baseball",
    "Basketball",
    "Boxing",
    "Cheerleading",
    "Cycling",
    "Fishing",
    "Fitness",
    "Football",
    "Golf",
    "Ice Skating",
    "Lacrosse",
    "Rugby",
    "Scuba Diving",
    "Skateboarding",
    "Surfing",
    "Swimming",
    "Table Tennis",
    "Tennis",
    "Volleyball",
    "Wrestling",
    "Animals",
    "Astronomy",
    "Autobiographical",
    "Biographical",
    "Body Horror",
    "Cannibalism",
    "Chibi",
    "Cosmic Horror",
    "Crime",
    "Crossover",
    "Death Game",
    "Denpa",
    "Drugs",
    "Economics",
    "Educational",
    "Environmental",
    "Ero Guro",
    "Gambling",
    "Gender Bending",
    "Gore",
    "LGBTQ+ Themes",
    "Lost Civilization",
    "Medicine",
    "Memory Manipulation",
    "Meta",
    "Noir",
    "Otaku Culture",
    "Pandemic",
    "Philosophy",
    "Politics",
    "Reincarnation",
    "Slavery",
    "Software Development",
    "Survival",
    "Terrorism",
    "War",
    "Assassins",
    "Cult",
    "Firefighters",
    "Gangs",
    "Mafia",
    "Military",
    "Police",
    "Triads",
    "Yakuza",
    "Aviation",
    "Cars",
    "Mopeds",
    "Motorcycles",
    "Ships",
    "Tanks",
    "Trains",
    "Age Gap",
    "Bisexual",
    "Boys' Love",
    "Harem",
    "Love Triangle",
    "Reverse Harem",
    "Teens' Love",
    "Yuri",
    "Cyberpunk",
    "Space Opera",
    "Time Manipulation",
    "Tokusatsu",
    "Real Robot",
    "Super Robot",
    "Cute Girls Doing Cute Things",
    "Family Life",
    "Iyashikei"
]
